#custom dockedr image for bitnami with pgvector
FROM pgvector/pgvector:pg16 AS builder

FROM bitnami/postgresql:17.4.0-debian-12-r15

COPY --from=builder /usr/lib/postgresql/16/lib/vector.so /opt/bitnami/postgresql/lib/
COPY --from=builder /usr/share/postgresql/16/extension/vector* /opt/bitnami/postgresql/share/extension/
